# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Protos import DbmsGrpc_pb2 as Protos_dot_DbmsGrpc__pb2
from Protos import Messages_pb2 as Protos_dot_Messages__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DbmsProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDatabase = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/CreateDatabase',
                request_serializer=Protos_dot_DbmsGrpc__pb2.DbNameRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetDatabase = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/GetDatabase',
                request_serializer=Protos_dot_DbmsGrpc__pb2.DbNameRequest.SerializeToString,
                response_deserializer=Protos_dot_Messages__pb2.DatabaseInfo.FromString,
                )
        self.DeleteDatabase = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/DeleteDatabase',
                request_serializer=Protos_dot_DbmsGrpc__pb2.DbNameRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.AddTable = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/AddTable',
                request_serializer=Protos_dot_DbmsGrpc__pb2.AddTableRequest.SerializeToString,
                response_deserializer=Protos_dot_DbmsGrpc__pb2.TableIdResponse.FromString,
                )
        self.RemoveTable = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/RemoveTable',
                request_serializer=Protos_dot_DbmsGrpc__pb2.TableReferenceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetTable = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/GetTable',
                request_serializer=Protos_dot_DbmsGrpc__pb2.TableReferenceRequest.SerializeToString,
                response_deserializer=Protos_dot_Messages__pb2.Table.FromString,
                )
        self.AddRow = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/AddRow',
                request_serializer=Protos_dot_DbmsGrpc__pb2.AddRowRequest.SerializeToString,
                response_deserializer=Protos_dot_DbmsGrpc__pb2.RowIdResponse.FromString,
                )
        self.RemoveRow = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/RemoveRow',
                request_serializer=Protos_dot_DbmsGrpc__pb2.RowReferenceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ValidateCell = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/ValidateCell',
                request_serializer=Protos_dot_DbmsGrpc__pb2.CellReferenceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateCell = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/UpdateCell',
                request_serializer=Protos_dot_DbmsGrpc__pb2.UpdateCellRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetTableDifference = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/GetTableDifference',
                request_serializer=Protos_dot_DbmsGrpc__pb2.TableDifferenceRequest.SerializeToString,
                response_deserializer=Protos_dot_Messages__pb2.Table.FromString,
                )
        self.TableExists = channel.unary_unary(
                '/DbmsGrpc.DbmsProcessor/TableExists',
                request_serializer=Protos_dot_DbmsGrpc__pb2.TableReferenceRequest.SerializeToString,
                response_deserializer=Protos_dot_DbmsGrpc__pb2.TableExistsResponse.FromString,
                )


class DbmsProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTableDifference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TableExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DbmsProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDatabase,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.DbNameRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatabase,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.DbNameRequest.FromString,
                    response_serializer=Protos_dot_Messages__pb2.DatabaseInfo.SerializeToString,
            ),
            'DeleteDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDatabase,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.DbNameRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddTable': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTable,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.AddTableRequest.FromString,
                    response_serializer=Protos_dot_DbmsGrpc__pb2.TableIdResponse.SerializeToString,
            ),
            'RemoveTable': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTable,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.TableReferenceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTable,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.TableReferenceRequest.FromString,
                    response_serializer=Protos_dot_Messages__pb2.Table.SerializeToString,
            ),
            'AddRow': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRow,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.AddRowRequest.FromString,
                    response_serializer=Protos_dot_DbmsGrpc__pb2.RowIdResponse.SerializeToString,
            ),
            'RemoveRow': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRow,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.RowReferenceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ValidateCell': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCell,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.CellReferenceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateCell': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCell,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.UpdateCellRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetTableDifference': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTableDifference,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.TableDifferenceRequest.FromString,
                    response_serializer=Protos_dot_Messages__pb2.Table.SerializeToString,
            ),
            'TableExists': grpc.unary_unary_rpc_method_handler(
                    servicer.TableExists,
                    request_deserializer=Protos_dot_DbmsGrpc__pb2.TableReferenceRequest.FromString,
                    response_serializer=Protos_dot_DbmsGrpc__pb2.TableExistsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DbmsGrpc.DbmsProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DbmsProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/CreateDatabase',
            Protos_dot_DbmsGrpc__pb2.DbNameRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/GetDatabase',
            Protos_dot_DbmsGrpc__pb2.DbNameRequest.SerializeToString,
            Protos_dot_Messages__pb2.DatabaseInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/DeleteDatabase',
            Protos_dot_DbmsGrpc__pb2.DbNameRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/AddTable',
            Protos_dot_DbmsGrpc__pb2.AddTableRequest.SerializeToString,
            Protos_dot_DbmsGrpc__pb2.TableIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/RemoveTable',
            Protos_dot_DbmsGrpc__pb2.TableReferenceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/GetTable',
            Protos_dot_DbmsGrpc__pb2.TableReferenceRequest.SerializeToString,
            Protos_dot_Messages__pb2.Table.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/AddRow',
            Protos_dot_DbmsGrpc__pb2.AddRowRequest.SerializeToString,
            Protos_dot_DbmsGrpc__pb2.RowIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/RemoveRow',
            Protos_dot_DbmsGrpc__pb2.RowReferenceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateCell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/ValidateCell',
            Protos_dot_DbmsGrpc__pb2.CellReferenceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/UpdateCell',
            Protos_dot_DbmsGrpc__pb2.UpdateCellRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTableDifference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/GetTableDifference',
            Protos_dot_DbmsGrpc__pb2.TableDifferenceRequest.SerializeToString,
            Protos_dot_Messages__pb2.Table.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TableExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DbmsGrpc.DbmsProcessor/TableExists',
            Protos_dot_DbmsGrpc__pb2.TableReferenceRequest.SerializeToString,
            Protos_dot_DbmsGrpc__pb2.TableExistsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
