# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/Types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12Protos/Types.proto\x12\x17\x44\x62msGrpc.Messages.Types\"\x06\n\x04\x43har\"\x07\n\x05\x43olor\"S\n\tColorInvl\x12\n\n\x02R1\x18\x01 \x01(\r\x12\n\n\x02R2\x18\x02 \x01(\r\x12\n\n\x02G1\x18\x03 \x01(\r\x12\n\n\x02G2\x18\x04 \x01(\r\x12\n\n\x02\x42\x31\x18\x05 \x01(\r\x12\n\n\x02\x42\x32\x18\x06 \x01(\r\"\t\n\x07Integer\"\x06\n\x04Real\"\x08\n\x06String\"\xd1\x02\n\x04Type\x12-\n\x04\x43har\x18\x01 \x01(\x0b\x32\x1d.DbmsGrpc.Messages.Types.CharH\x00\x12/\n\x05\x43olor\x18\x02 \x01(\x0b\x32\x1e.DbmsGrpc.Messages.Types.ColorH\x00\x12\x37\n\tColorInvl\x18\x03 \x01(\x0b\x32\".DbmsGrpc.Messages.Types.ColorInvlH\x00\x12\x33\n\x07Integer\x18\x04 \x01(\x0b\x32 .DbmsGrpc.Messages.Types.IntegerH\x00\x12-\n\x04Real\x18\x05 \x01(\x0b\x32\x1d.DbmsGrpc.Messages.Types.RealH\x00\x12\x31\n\x06String\x18\x06 \x01(\x0b\x32\x1f.DbmsGrpc.Messages.Types.StringH\x00\x12\r\n\x05ToStr\x18\x07 \x01(\tB\n\n\x08Instanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.Types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHAR']._serialized_start=47
  _globals['_CHAR']._serialized_end=53
  _globals['_COLOR']._serialized_start=55
  _globals['_COLOR']._serialized_end=62
  _globals['_COLORINVL']._serialized_start=64
  _globals['_COLORINVL']._serialized_end=147
  _globals['_INTEGER']._serialized_start=149
  _globals['_INTEGER']._serialized_end=158
  _globals['_REAL']._serialized_start=160
  _globals['_REAL']._serialized_end=166
  _globals['_STRING']._serialized_start=168
  _globals['_STRING']._serialized_end=176
  _globals['_TYPE']._serialized_start=179
  _globals['_TYPE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
